trigger:
- main

variables:
- name: tf_folder
  value: $(System.DefaultWorkingDirectory)/13_storage_blob 

pool:
  vmImage: ubuntu-latest

steps:

- task
  displayName: 'Install checkov'
    inputs:
      targetType: 'inline'
      script: 'pip3 install checkov'

- task: Bash@3
  displayName: 'Checkov Static Code Analysis'
  inputs:
    targetType: 'inline'
    script: | 
    mkdir checkov-report
       checkov -d . --skip-path ./*.json --check MEDIUM --output junitxml > $(System.DefaultWorkingDirectory)/checkov-report/TEST-checkov-report.xml

- task: PublishTestResults@2
  displayName: 'Publish checkov Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFile: '**/TEST-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/checkov-report'
    mergeTestResults: false
    testRuntitle: CheckOV Scan
    failTaskOnFailedTests: false
    publishRunAttachements: true